export const AUTH_RESEND_VERIFICATION_REQUEST = 'AUTH_RESEND_VERIFICATION_REQUEST'
export const AUTH_RESEND_VERIFICATION_SUCCESS = 'AUTH_RESEND_VERIFICATION_SUCCESS'
export const AUTH_RESEND_VERIFICATION_FAILURE = 'AUTH_RESEND_VERIFICATION_FAILURE'

export const AUTH_SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST'
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE'

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'

export const AUTH_REFRESH_REQUEST = 'AUTH_REFRESH_REQUEST'
export const AUTH_REFRESH_SUCCESS = 'AUTH_REFRESH_SUCCESS'
export const AUTH_REFRESH_FAILURE = 'AUTH_REFRESH_FAILURE'

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'

export const AUTH_FINGERPRINT_REQUEST = 'AUTH_FINGERPRINT_REQUEST'
export const AUTH_FINGERPRINT_SUCCESS = 'AUTH_FINGERPRINT_SUCCESS'
export const AUTH_FINGERPRINT_FAILURE = 'AUTH_FINGERPRINT_FAILURE'